[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Py2048"
version = "0.1.0"
description = "Python clone of 2048"
authors = [
    {name = "Michael Buckley"}
]
requires-python = ">=3.8"
dependencies = [
    "pygame"
]
keywords = ["2048", "game"]

[tool.hatch.build.targets.wheel]
packages = ["py2048"]
